# Usar uma imagem oficial do Python
FROM python:3.11

# Definir o diretório de trabalho no container
WORKDIR /app

# Copiar apenas os arquivos essenciais para instalação
COPY back-end/requirements.txt .

# Instalar dependências
RUN pip install --no-cache-dir -r requirements.txt

# Copiar todo o código do backend
COPY ../back-end/ .

# Expor a porta do FastAPI
EXPOSE 8080

# Comando para rodar a aplicação
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8080", "--reload"]
