# Usando uma versão recente do Node.js
FROM node:18

# Criando diretório de trabalho dentro do container
WORKDIR /app

# Copiando package.json e package-lock.json antes de copiar o código
COPY ../front-end/package*.json ./

# Instalando dependências
RUN npm install

# Copiando todo o código do frontend
COPY ../front-end/ .

# Expondo a porta 3000
EXPOSE 3000

# Corrigindo o comando para rodar o React corretamente
CMD ["npm", "start"]
